linters:
  enable:
    - exportloopref
    - gocritic
    - gofmt
    - gofumpt
    - goimports
    - makezero
    - nestif
    - revive
    - whitespace
    - nilnil
    - errname
    - errorlint
    - goerr113
    - ireturn
  disable:
    - deadcode
    - errcheck
    - structcheck
    - unused

linters-settings:
  revive:
    rules:
      - name: unused-parameter
        disabled: true
