version: "2"
linters:
  enable:
    - err113
    - errname
    - errorlint
    - gocritic
    - ireturn
    - makezero
    - nestif
    - nilnil
    - revive
    - whitespace
  disable:
    - errcheck
    - unused
  settings:
    revive:
      rules:
        - name: unused-parameter
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
