builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

release:
  github:
    owner: mikelorant
    name: committed

brews:
  - tap:
      owner: mikelorant
      name: homebrew-committed
    homepage: https://github.com/mikelorant/committed
    description: >-
      WYSIWYG Git commit editor that helps improve the quality of your
      commits by showing you the layout in the same format as git log
    license: MIT
    dependencies:
      - name: git
    test: |
      system "#{bin}/committed --help"
