FROM alpine:3.21.3 AS release
ENV TERM=xterm-256color
RUN apk add --no-cache \
      git=~2
COPY committed /usr/local/bin/

FROM release AS test
WORKDIR /root/repository
RUN git config --global user.email "you@example.com" && \
    git config --global user.name "Your Name" && \
    git init

ENTRYPOINT ["committed"]
