FROM alpine:3.17.2 as release
ENV TERM=xterm-256color
RUN apk add --no-cache \
      git=2.38.4-r1
COPY committed /usr/local/bin/

FROM release as test
WORKDIR /root/repository
RUN git config --global user.email "you@example.com" && \
    git config --global user.name "Your Name" && \
    git init

ENTRYPOINT ["committed"]
